"""
Backscattering heat map as a function of the period L/lambda and the dielectric constant (Results section).

Profile shape fixed: z = a cos(Kx) + b cos(Lambda K x + phi), a = 0.03 L, b = 0.004 L, Lambda = 5; only lambda/L is varied
(so the slopes, a K = 0.19, are the same for every period and k b = 0.025 L/lambda).
Backscattering condition (Littrow): the Floquet order r = -Lambda points back to the source, alpha_r = -alpha, i.e.
    sin(theta_i) = Lambda * lambda / (2 L)    (needs L > Lambda*lambda/2),
so the angle of incidence follows the period.  The quantity mapped is the efficiency of that order,
    e_back = (beta_r / beta) |B_r|^2 = |B_{-Lambda}|^2        (beta_r = beta).
The phase phi of the small-scale component relative to the smooth one is either fixed (phi = 0) or averaged over 8 equispaced
values (random relative phase: the incoherent, "random-surface" backscattered intensity).

usage:  python backscatter_map.py compute | plot | summary
"""
import os, sys, time
import numpy as np
from multiprocessing import Pool
from scattering import *

HERE = os.path.dirname(os.path.abspath(__file__))          # paths are relative to this file, not to the working directory
DATA = os.path.join(HERE, "data")                           # cached results (small; regenerated by the scripts)
FIG = os.path.join(HERE, "figures")                         # output figures
os.makedirs(DATA, exist_ok=True); os.makedirs(FIG, exist_ok=True)

LAM, A_L, B_L = 5, 0.03, 0.004
L_REL = np.arange(3.0, 15.0 + 1e-9, 0.1) + 0.013       # offset: avoid exact Wood anomalies (half-integer L/lambda)
EPS = np.linspace(1.5, 10.0, 24)
PHASES = 2 * np.pi * np.arange(8) / 8
POLS = ("TE", "TM")
MARGIN, N = 12, 2048
FILE = os.path.join(DATA, "backscatter_map.npz")


def make_problem(Lrel, eps, pol):
    wl = 1.0 / Lrel
    th = np.arcsin(LAM * wl / 2)
    p0 = Problem(1.0, wl, th, eps, pol, 30, N=N)
    rmax = max(int(np.abs(p0.r[p0.prop_m]).max()) + MARGIN, 30)
    return Problem(1.0, wl, th, eps, pol, rmax, N=N), th


def cell(args):
    iL, iE, ip = args
    Lrel, eps, pol = L_REL[iL], EPS[iE], POLS[ip]
    out = np.full((5, len(PHASES)), np.nan)          # rows: ref, KA, MVB n=1, 2, 3
    try:
        with np.errstate(all="ignore"):
            p, th = make_problem(Lrel, eps, pol)
            f, f1 = cos_surface(p, A_L)
            Bk = ka_amplitudes(p, f, f1)
            i = p.rmax - LAM
            for j, ph in enumerate(PHASES):
                z = B_L * np.cos(LAM * p.K * p.x + ph)
                z1 = -B_L * LAM * p.K * np.sin(LAM * p.K * p.x + ph)
                Bex = rayleigh_exact(p, f + z, f1 + z1)
                dp, dm = mvb_coefficients(p, f, f1, z, z1, Bk, 3)
                out[0, j] = abs(Bex[0][i]) ** 2
                out[1, j] = abs(Bk[0][i]) ** 2
                for n in (1, 2, 3):
                    out[1 + n, j] = abs(mvb_sum(dp, dm, 1.0, n)[0][i]) ** 2
    except Exception:
        pass
    return iL, iE, ip, out


def compute():
    tasks = [(iL, iE, ip) for ip in range(len(POLS)) for iE in range(len(EPS)) for iL in range(len(L_REL))]
    data = np.full((len(POLS), len(EPS), len(L_REL), 5, len(PHASES)), np.nan)
    t0 = time.time()
    with Pool(8) as pool:
        for k, (iL, iE, ip, out) in enumerate(pool.imap_unordered(cell, tasks, chunksize=8)):
            data[ip, iE, iL] = out
            if k % 400 == 0:
                print(f"{k}/{len(tasks)}  {time.time() - t0:.0f}s", flush=True)
    theta = np.rad2deg(np.arcsin(LAM / (2 * L_REL)))
    np.savez(FILE, data=data, L=L_REL, eps=EPS, phases=PHASES, theta=theta, pols=POLS)
    print("saved", FILE, " non-finite cells:", int((~np.isfinite(data)).any(axis=(3, 4)).sum()))


def plot(fname=os.path.join(FIG, "fig_backscatter.pdf"), fname0=os.path.join(FIG, "fig_backscatter_phi0.pdf"),
         fname_te=os.path.join(FIG, "fig_backscatter_te.pdf")):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.colors import TwoSlopeNorm
    plt.rcParams.update({"text.usetex": True, "font.family": "serif",
                         "text.latex.preamble": r"\usepackage{mathpazo}\usepackage{amsmath}",
                         "font.size": 8, "figure.dpi": 130})
    d = np.load(FILE)
    data, L, eps = d["data"], d["L"], d["eps"]
    to_theta = lambda x: np.degrees(np.arcsin(np.clip(LAM / (2 * np.asarray(x, float)), -1, 1)))
    to_L = lambda t: LAM / (2 * np.sin(np.radians(np.asarray(t, float))))

    def make(sel, fn, vmin_ratio, pols=(0, 1), height=4.7):
        fig, axs = plt.subplots(len(pols), 3, figsize=(7.2, height), sharex=True, sharey=True, squeeze=False)
        for row, ip in enumerate(pols):
            pol = POLS[ip]
            ref, ka, m3 = (sel(data[ip, :, :, k, :]) for k in (0, 1, 4))
            panels = [
                (np.log10(ref), r"$\log_{10}\,e_{\rm back}$ (exact)", dict(cmap="viridis")),
                (np.log10(ref / ka), r"$\log_{10}(e_{\rm exact}/e_{\rm KA})$",
                 dict(cmap="RdBu_r", norm=TwoSlopeNorm(0, vmin=vmin_ratio, vmax=5.5))),
                (100 * (m3 / ref - 1), r"error of KA+MVB, $n\leq3$ (\%)", dict(cmap="PuOr", vmin=-20, vmax=20)),
            ]
            for ic, (val, lab, kw) in enumerate(panels):
                ax = axs[row, ic]
                im = ax.pcolormesh(L, eps, val, shading="nearest", rasterized=True, **kw)
                cb = fig.colorbar(im, ax=ax, pad=0.02); cb.ax.tick_params(labelsize=6)
                cb.set_label(lab, fontsize=7)
                for w in np.arange(3.5, 15, 1.0):          # Wood anomalies (an order at grazing) occur at half-integer L/lambda
                    ax.axvline(w, color="w", lw=0.3, alpha=0.5)
                ax.text(0.04, 0.92, "(%s) %s" % ("abcdef"[3 * row + ic], pol), transform=ax.transAxes, fontsize=8,
                        bbox=dict(fc="w", alpha=0.75, lw=0, pad=1.5))
                if row == len(pols) - 1:
                    ax.set_xlabel(r"$L/\lambda$")
                if ic == 0:
                    ax.set_ylabel(r"$\epsilon$")
                if row == 0:
                    sec = ax.secondary_xaxis("top", functions=(to_theta, to_L))
                    sec.tick_params(labelsize=6)
                    sec.set_xticks([10, 15, 20, 30, 50])
                    sec.set_xlabel(r"$\theta_i$ (deg)", fontsize=7)
        fig.tight_layout(); fig.savefig(fn)
        plt.close(fig)

    make(lambda a: a.mean(axis=-1), fname, -1.0)
    make(lambda a: a.mean(axis=-1), fname_te, -1.0, pols=(0,), height=2.3)
    make(lambda a: a[..., 0], fname0, -3.5)


def summary():
    d = np.load(FILE)
    data, L, eps = d["data"], d["L"], d["eps"]
    for tag, sel in (("phase-averaged", lambda a: a.mean(axis=-1)), ("phi = 0", lambda a: a[..., 0])):
        print("==", tag)
        for ip, pol in enumerate(POLS):
            ref, ka, m1, m2, m3 = (sel(data[ip, :, :, k, :]) for k in range(5))
            ok = np.isfinite(ref) & np.isfinite(m3)
            err = np.abs(m3 / ref - 1)
            for lo, hi in ((3, 4), (4, 6), (6, 10), (10, 15.1)):
                msk = ok & ((L[None, :] >= lo) & (L[None, :] < hi))
                print(f"  {pol} L/lambda in [{lo},{hi}): median |err| n<=3 {np.median(err[msk]) * 100:.2f}%  90th pct "
                      f"{np.percentile(err[msk], 90) * 100:.2f}%  max {err[msk].max() * 100:.1f}% | enhancement ref/KA: "
                      f"median {np.median((ref / ka)[msk]):.3g}  max {(ref / ka)[msk].max():.3g}  min {(ref / ka)[msk].min():.3g}")
            print(f"  {pol}: fraction of cells with |err|<5%: {np.mean(err[ok] < 0.05):.3f}, <10%: {np.mean(err[ok] < 0.10):.3f}; "
                  f"non-finite cells {int((~ok).sum())}")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "plot"
    {"compute": compute, "plot": plot, "summary": summary}[cmd]()
