"""
Dependence on the dielectric constant for a given profile (Results section). It computes the scan that feeds
Fig. 3(c) (saved in data/dielectric_scan.npy, read by make_final_figures.py) and prints the statistics quoted in the text;
it also draws figures/fig_eps.pdf, a more detailed version of that panel that is not in the paper.

Profile (fixed): z = a cos(Kx) + b cos(Lambda K x),  a = 0.03 L, b = 0.004 L, Lambda = 5, L = 10 lambda,
theta_i = 20 deg.  eps is scanned from 1.2 to 16, TE and TM.
For every eps we compute the reference (Rayleigh) solution of the full profile, KA of the smooth profile and the
KA + MVB series (n <= 3), and report
  * efficiencies of selected reflected orders,
  * relative L1 error (over all propagating orders) of the reflected and of the transmitted orders.
The number of retained Rayleigh orders follows the number of propagating transmitted orders:
rmax = max(r_trans + MARGIN, 30).
"""
import os, sys
import numpy as np
from multiprocessing import Pool
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scattering import *

HERE = os.path.dirname(os.path.abspath(__file__))          # paths are relative to this file, not to the working directory
DATA = os.path.join(HERE, "data")                           # cached results (small; regenerated by the scripts)
FIG = os.path.join(HERE, "figures")                         # output figures
os.makedirs(DATA, exist_ok=True); os.makedirs(FIG, exist_ok=True)

WL_REL, A_L, B_L, LAM, TH = 0.1, 0.03, 0.004, 5, 20.0     # lambda/L, a/L, b/L, Lambda, theta_i (deg)
ORDERS = (0, -3, -8, -12)                                  # reflected orders shown
MARGIN, N = 12, 2048
EPS = np.geomspace(1.2, 16.0, 36)


def l1(e, er, m):
    return np.abs(e - er)[m].sum() / er[m].sum()


def one(args):
    eps, pol = args
    p0 = Problem(1.0, WL_REL, np.deg2rad(TH), eps, pol, 30, N=N)
    rmax = max(int(np.abs(p0.r[p0.prop_m]).max()) + MARGIN, 30)
    p = Problem(1.0, WL_REL, np.deg2rad(TH), eps, pol, rmax, N=N)
    f, f1 = cos_surface(p, A_L * 1.0)
    z, z1 = cos_surface(p, B_L * 1.0, LAM)
    Bex = rayleigh_exact(p, f + z, f1 + z1)
    Bka = ka_amplitudes(p, f, f1)
    dp, dm = mvb_coefficients(p, f, f1, z, z1, Bka, 3)
    ex = efficiencies(p, *Bex)
    out = {"eps": eps, "pol": pol, "rmax": rmax, "energy": ex[0].sum() + ex[1].sum() - 1}
    cases = {"ka": Bka}
    for n in (1, 2, 3):
        cases[n] = mvb_sum(dp, dm, 1.0, n)
    for k, B in cases.items():
        e = efficiencies(p, *B)
        out[f"errR_{k}"] = l1(e[0], ex[0], p.prop_p)
        out[f"errT_{k}"] = l1(e[1], ex[1], p.prop_m)
        if k in ("ka", 3):
            out[f"R_{k}"] = e[0].sum(); out[f"T_{k}"] = e[1].sum()
            out[f"orders_{k}"] = np.array([e[0][p.rmax + r] for r in ORDERS])
    out["R_ref"], out["T_ref"] = ex[0].sum(), ex[1].sum()
    out["orders_ref"] = np.array([ex[0][p.rmax + r] for r in ORDERS])
    return out


def run():
    jobs = [(e, pol) for pol in ("TE", "TM") for e in EPS]
    with Pool(8) as pool:
        res = pool.map(one, jobs)
    return {pol: [r for r in res if r["pol"] == pol] for pol in ("TE", "TM")}


def plot(res, fname=os.path.join(FIG, "fig_eps.pdf")):
    plt.rcParams.update({"font.size": 8, "axes.grid": True, "grid.alpha": .3, "figure.dpi": 130})
    fig, axs = plt.subplots(2, 2, figsize=(7.2, 5.4))
    cols = ["k", "tab:blue", "tab:green", "tab:red"]
    eps = np.array([r["eps"] for r in res["TE"]])
    for ax, pol in zip(axs[0], ("TE", "TM")):
        for j, (r, c) in enumerate(zip(ORDERS, cols)):
            ref = np.array([x["orders_ref"][j] for x in res[pol]])
            ka = np.array([x["orders_ka"][j] for x in res[pol]])
            mv = np.array([x["orders_3"][j] for x in res[pol]])
            ax.semilogy(eps, ka, "--", color=c, lw=1)
            ax.semilogy(eps, mv, "-", color=c, lw=1.3, label=f"$r={r}$")
            ax.semilogy(eps[::2], ref[::2], "o", color=c, ms=3, mfc="none")
        ax.set_xscale("log"); ax.set_xlabel("$\\epsilon$"); ax.set_title("(a) TE" if pol == "TE" else "(b) TM")
        ax.set_ylim(1e-8, 1)
    axs[0, 0].set_ylabel("efficiency $e^+_r$")
    axs[0, 0].legend(fontsize=7, ncol=2, loc="lower right", title="KA+MVB (line), KA (dashed), exact (o)",
                     title_fontsize=6)
    sty = {"ka": ("b", "KA"), 1: ("g", "$n\\leq1$"), 2: ("orange", "$n\\leq2$"), 3: ("r", "$n\\leq3$")}
    for ax, key, title in zip(axs[1], ("errR", "errT"), ("reflected orders", "transmitted orders")):
        for k, (c, lab) in sty.items():
            for pol, ls in (("TE", "-"), ("TM", ":")):
                v = [x[f"{key}_{k}"] for x in res[pol]]
                ax.loglog(eps, v, ls, color=c, lw=1.2, label=lab if pol == "TE" else None)
        ax.set_xlabel("$\\epsilon$"); ax.set_title(("(c) " if key == "errR" else "(d) ") + title + " (TE solid, TM dotted)")
    axs[1, 0].set_ylabel("relative error"); axs[1, 0].legend(fontsize=7, ncol=2)
    from matplotlib.ticker import FixedLocator, FixedFormatter, NullLocator
    ticks = [1.2, 2, 3, 5, 8, 12, 16]
    for ax in axs.ravel():
        ax.xaxis.set_major_locator(FixedLocator(ticks)); ax.xaxis.set_major_formatter(FixedFormatter([str(t) for t in ticks]))
        ax.xaxis.set_minor_locator(NullLocator())
    fig.tight_layout(); fig.savefig(fname)


def diagnostic(eps_list=(2.25, 6.0, 12.0), pol="TE"):
    """Why does the KA error of the transmitted orders grow with eps?  Compare, for the transmitted orders,
    (i) KA vs exact for the SMOOTH profile alone, (ii) the effect of the small scale on the exact spectrum
    (exact smooth vs exact smooth+rough), which is what KA on the smooth profile cannot see."""
    print(f"transmitted orders, {pol}: relative L1 differences")
    print(f"{'eps':>6} | KA vs exact (smooth only) | exact smooth vs exact smooth+rough | KA vs exact (full) | KA+MVB n<=3 vs exact (full)")
    for eps in eps_list:
        p0 = Problem(1.0, WL_REL, np.deg2rad(TH), eps, pol, 30, N=N)
        rmax = max(int(np.abs(p0.r[p0.prop_m]).max()) + MARGIN, 30)
        p = Problem(1.0, WL_REL, np.deg2rad(TH), eps, pol, rmax, N=N)
        f, f1 = cos_surface(p, A_L); z, z1 = cos_surface(p, B_L, LAM)
        Bka = ka_amplitudes(p, f, f1)
        es, ef = efficiencies(p, *rayleigh_exact(p, f, f1)), efficiencies(p, *rayleigh_exact(p, f + z, f1 + z1))
        dp, dm = mvb_coefficients(p, f, f1, z, z1, Bka, 3)
        ek, em = efficiencies(p, *Bka), efficiencies(p, *mvb_sum(dp, dm, 1.0, 3))
        m = p.prop_m
        print(f"{eps:6.2f} | {l1(ek[1], es[1], m):25.4f} | {l1(es[1], ef[1], m):34.4f} | {l1(ek[1], ef[1], m):18.4f} | {l1(em[1], ef[1], m):.4f}")


if __name__ == "__main__":
    res = run()
    np.save(os.path.join(DATA, "dielectric_scan.npy"), res, allow_pickle=True)
    plot(res)
    print(f"{'pol':>3} {'eps':>6} {'rmax':>4} | reflected: {'KA':>6} {'n<=1':>6} {'n<=2':>7} {'n<=3':>7} | transmitted: {'KA':>6} {'n<=1':>6} {'n<=2':>7} {'n<=3':>7} | R_ex  R_KA  R_MVB | T_ex  T_KA  T_MVB | R+T-1")
    for pol in ("TE", "TM"):
        for r in res[pol][::3]:
            print(f"{pol:>3} {r['eps']:6.2f} {r['rmax']:4d} | {r['errR_ka']:17.3f} {r['errR_1']:6.3f} {r['errR_2']:7.4f} {r['errR_3']:7.4f} | "
                  f"{r['errT_ka']:19.3f} {r['errT_1']:6.3f} {r['errT_2']:7.4f} {r['errT_3']:7.4f} | "
                  f"{r['R_ref']:.4f} {r['R_ka']:.4f} {r['R_3']:.4f} | {r['T_ref']:.4f} {r['T_ka']:.4f} {r['T_3']:.4f} | {r['energy']:.0e}")
    diagnostic()
    for pol in ("TE", "TM"):
        for key in ("errR", "errT"):
            print(pol, key, "range over eps: KA %.3f-%.3f | n<=3 %.4f-%.4f" % (
                min(r[key + "_ka"] for r in res[pol]), max(r[key + "_ka"] for r in res[pol]),
                min(r[key + "_3"] for r in res[pol]), max(r[key + "_3"] for r in res[pol])))
