"""
Final (merged) figures of the Results section, to stay within the page limit:
  fig_spectra.pdf : (a) TE, (b) TM spectrum of the periodic two-scale profile; (c) one random multi-scale realisation;
                    (d) ensemble average over random roughness: analytic (MVB) vs Monte Carlo (exact solver) vs KA
  fig_robust.pdf  : (a) error vs roughness amplitude and perturbation order; (b) error vs incidence angle;
                    (c) error vs dielectric constant, reflected and transmitted orders
All the statistics quoted in the text are printed.
"""
import os, sys, time
import numpy as np
from multiprocessing import Pool
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scattering import *
from ensemble import *

plt.rcParams.update({"text.usetex": True, "font.family": "serif",
                     "text.latex.preamble": r"\usepackage{mathpazo}\usepackage{amsmath}",
                     "font.size": 8, "axes.grid": True, "grid.alpha": .3, "axes.titlesize": 8,
                     "legend.fontsize": 6.5, "xtick.labelsize": 7, "ytick.labelsize": 7})
HERE = os.path.dirname(os.path.abspath(__file__))          # paths are relative to this file, not to the working directory
DATA = os.path.join(HERE, "data")                           # cached results (small; regenerated by the scripts)
FIG = os.path.join(HERE, "figures")                         # output figures
os.makedirs(DATA, exist_ok=True); os.makedirs(FIG, exist_ok=True)
OUT = os.path.join(FIG, "")
WL, A, B, LAM, EPS0, N = 0.1, 0.03, 0.004, 5, 2.25, 2048
C_KA, C_1, C_2, C_3, C_EX = "tab:blue", "tab:green", "tab:orange", "tab:red", "k"


def l1(e, er, m):
    return np.abs(e - er)[m].sum() / er[m].sum()


def eff_p(p, Bp):
    return efficiencies(p, Bp, np.zeros_like(Bp))[0]


# ------------------------------------------------------------------ random profile (same generator/seed as before)
def random_profile(p, seed=3):
    rng = np.random.default_rng(seed)
    def rp(kmin, kmax, amp, decay):
        g = np.zeros(p.N); g1 = np.zeros(p.N)
        for m in range(kmin, kmax + 1):
            am = amp * (m / kmin) ** (-decay) * rng.normal(); ph = rng.uniform(0, 2 * np.pi)
            g += am * np.cos(m * p.K * p.x + ph); g1 -= am * m * p.K * np.sin(m * p.K * p.x + ph)
        return g, g1
    f, f1 = rp(1, 3, 0.012, 1.0)
    z, z1 = rp(4, 10, 0.0030, 0.5)
    return f, f1, z, z1


def mc_chunk(args):
    seed, k, harm = args
    p = Problem(1.0, WL, np.deg2rad(25), EPS0, "TE", 40, N=N)
    f, f1, _, _ = random_profile(p)
    return monte_carlo(p, f, f1, harm, k, seed=seed)


# ------------------------------------------------------------------ Fig. spectra
def fig_spectra():
    fig, axs = plt.subplots(2, 2, figsize=(7.2, 4.5), sharey=True)
    stats = {}
    for ax, pol in zip(axs[0], ("TE", "TM")):
        p = Problem(1.0, WL, np.deg2rad(20), EPS0, pol, 40, N=N)
        f, f1 = cos_surface(p, A); z, z1 = cos_surface(p, B, LAM)
        Bex = rayleigh_exact(p, f + z, f1 + z1); Bka = ka_amplitudes(p, f, f1)
        dp, dm = mvb_coefficients(p, f, f1, z, z1, Bka, 3)
        s = p.prop_p; r = p.r[s]
        ax.semilogy(r, eff_p(p, Bka[0])[s], "--", color=C_KA, lw=1.1, label="KA")
        ax.semilogy(r, eff_p(p, mvb_sum(dp, dm, 1, 1)[0])[s], "-.", color=C_1, lw=1.1, label=r"KA+MVB, $n\leq1$")
        ax.semilogy(r, eff_p(p, mvb_sum(dp, dm, 1, 3)[0])[s], "-", color=C_3, lw=1.2, label=r"KA+MVB, $n\leq3$")
        ax.semilogy(r, np.maximum(eff_p(p, Bex[0])[s], 1e-14), "o", color=C_EX, ms=2.8, mfc="none", label="exact")
        ex = eff_p(p, Bex[0])
        stats[pol] = [l1(eff_p(p, Bka[0]), ex, s)] + [l1(eff_p(p, mvb_sum(dp, dm, 1, n)[0]), ex, s) for n in (1, 2, 3)]
        ax.set_title(r"(%s) %s, periodic profile" % ("a" if pol == "TE" else "b", pol))
    # (c) one random realisation, (d) ensemble
    p = Problem(1.0, WL, np.deg2rad(25), EPS0, "TE", 40, N=N)
    f, f1, z, z1 = random_profile(p)
    Bex = rayleigh_exact(p, f + z, f1 + z1); Bka = ka_amplitudes(p, f, f1)
    op = SmoothOperator(p, f, f1)
    dp, dm = mvb_coefficients(p, f, f1, z, z1, Bka, 3, smooth=op)
    s = p.prop_p; r = p.r[s]
    ex = eff_p(p, Bex[0])
    ax = axs[1, 0]
    ax.semilogy(r, eff_p(p, Bka[0])[s], "--", color=C_KA, lw=1.1)
    ax.semilogy(r, eff_p(p, mvb_sum(dp, dm, 1, 3)[0])[s], "-", color=C_3, lw=1.2)
    ax.semilogy(r, ex[s], "o", color=C_EX, ms=2.8, mfc="none")
    ax.set_title(r"(c) TE, random multi-scale profile (one realisation)")
    stats["random"] = [l1(eff_p(p, Bka[0]), ex, s)] + [l1(eff_p(p, mvb_sum(dp, dm, 1, n)[0]), ex, s) for n in (1, 2, 3)]
    stats["random_R"] = (ex.sum(), eff_p(p, Bka[0]).sum(), eff_p(p, mvb_sum(dp, dm, 1, 3)[0]).sum())
    stats["random_rms_slope"] = (f1.std(), (f1 + z1).std(), p.k * z.std())
    # ensemble over random phases of the small scale (same smooth profile)
    harm = [(m, 0.003 * (m / 4) ** (-0.5)) for m in range(4, 11)]
    t = time.perf_counter()
    (Ip, Im), _ = analytic_average(p, f, f1, Bka, harm, smooth=op)
    t_an = time.perf_counter() - t
    ep_an, em_an = to_efficiency(p, Ip, Im)
    K_MC, nproc = 2000, 8
    t = time.perf_counter()
    with Pool(nproc) as pool:
        res = pool.map(mc_chunk, [(100 + i, K_MC // nproc, harm) for i in range(nproc)])
    t_mc_wall = time.perf_counter() - t
    mp = np.mean([x[0] for x in res], axis=0); mm = np.mean([x[1] for x in res], axis=0)
    err = np.sqrt(np.mean([x[2] ** 2 for x in res], axis=0) / nproc)
    ax = axs[1, 1]
    ax.semilogy(r, eff_p(p, Bka[0])[s], "--", color=C_KA, lw=1.1)
    ax.semilogy(r, ep_an[s], "-", color=C_3, lw=1.2)
    ax.errorbar(r, mp[s], yerr=2 * err[s], fmt="o", color=C_EX, ms=2.8, mfc="none", lw=0.7, capsize=1.5)
    ax.set_title(r"(d) ensemble average over random roughness")
    m = s & (mp > 1e-7)
    stats["ens"] = dict(an=l1(ep_an, mp, m), ka=l1(eff_p(p, Bka[0]), mp, m), se=np.sqrt((err[m] ** 2).sum()) / mp[m].sum(),
                        t_an=t_an, t_mc_wall=t_mc_wall, K=K_MC, n_runs=3 * len(harm),
                        trans=np.abs(em_an - mm)[p.prop_m].sum() / mm[p.prop_m].sum(),
                        worst_order=float(np.max(np.abs(ep_an[m] / mp[m] - 1))))
    from matplotlib.ticker import MaxNLocator
    for ax in axs.ravel():
        ax.xaxis.set_major_locator(MaxNLocator(integer=True))
    for ax in axs[1]:
        ax.set_xlabel(r"Floquet order $r$")
    for ax in axs[:, 0]:
        ax.set_ylabel(r"efficiency $e^+_r$")
    for ax in axs.ravel():
        ax.set_ylim(1e-8, 0.1)
    # one legend for all panels (same line styles), above the figure so that it covers no curve
    h, l = axs[0, 0].get_legend_handles_labels()
    fig.legend(h, l, loc="upper center", ncol=4, frameon=False, handlelength=2.4, columnspacing=2.2)
    fig.tight_layout(rect=(0, 0, 1, 0.945)); fig.savefig(OUT + "fig_spectra.pdf"); plt.close(fig)
    return stats


# ------------------------------------------------------------------ Fig. robust
def angle_job(th):
    p = Problem(1.0, WL, np.deg2rad(th), EPS0, "TE", 40, N=N)
    f, f1 = cos_surface(p, A); z, z1 = cos_surface(p, B, LAM)
    Bex = rayleigh_exact(p, f + z, f1 + z1); Bka = ka_amplitudes(p, f, f1)
    dp, dm = mvb_coefficients(p, f, f1, z, z1, Bka, 3)
    ex = eff_p(p, Bex[0]); s = p.prop_p
    out = [l1(eff_p(p, Bka[0]), ex, s)] + [l1(eff_p(p, mvb_sum(dp, dm, 1, n)[0]), ex, s) for n in (1, 2, 3)]
    bk = s & (p.alpha_r < 0)
    back = [eff_p(p, Bka[0])[bk].sum(), eff_p(p, mvb_sum(dp, dm, 1, 3)[0])[bk].sum(), ex[bk].sum()]
    return out, back


def conv_job(b):
    p = Problem(1.0, WL, np.deg2rad(20), EPS0, "TE", 40, N=N)
    f, f1 = cos_surface(p, A); z, z1 = cos_surface(p, b, LAM)
    Bex = rayleigh_exact(p, f + z, f1 + z1); Bka = ka_amplitudes(p, f, f1)
    dp, dm = mvb_coefficients(p, f, f1, z, z1, Bka, 4)
    ex = eff_p(p, Bex[0]); s = p.prop_p
    return [l1(eff_p(p, Bka[0]), ex, s)] + [l1(eff_p(p, mvb_sum(dp, dm, 1, n)[0]), ex, s) for n in (1, 2, 3, 4)]


def fig_robust():
    stats = {}
    fig, axs = plt.subplots(1, 3, figsize=(7.2, 2.5))
    # (a) convergence
    bs = np.array([0.001, 0.002, 0.004, 0.008, 0.016]); kb = 2 * np.pi / WL * bs
    import os
    cache = os.path.join(DATA, "final_robust_cache.npz")
    ths = np.linspace(2.13, 60.07, 59)
    if os.path.exists(cache) and "--replot" in sys.argv:
        d = np.load(cache); E, Ea, Ba = d["E"], d["Ea"], d["Ba"]
    else:
        with Pool(8) as pool:
            E = np.array(pool.map(conv_job, bs))
            out = pool.map(angle_job, ths)
        Ea = np.array([o[0] for o in out]); Ba = np.array([o[1] for o in out])
        np.savez(cache, E=E, Ea=Ea, Ba=Ba)
    ax = axs[0]
    ax.loglog(kb, E[:, 0], "--s", color=C_KA, ms=3, lw=1.1, label="KA")
    for n, c in ((1, C_1), (2, C_2), (3, C_3), (4, "tab:purple")):
        ax.loglog(kb, E[:, n], "-o", color=c, ms=3, lw=1.1, label=r"$n\leq%d$" % n)
    ax.set_xlabel(r"$kb$"); ax.set_ylabel("relative error"); ax.set_title(r"(a) roughness amplitude")
    ax.legend(ncol=1)
    stats["conv"] = (kb, E)
    # (b) incidence angle
    ax = axs[1]
    ax.semilogy(ths, Ea[:, 0], "--", color=C_KA, lw=1.1)
    for n, c in ((1, C_1), (2, C_2), (3, C_3)):
        ax.semilogy(ths, Ea[:, n], "-", color=c, lw=1.1)
    ax.set_xlabel(r"$\theta_i$ (deg)"); ax.set_title(r"(b) incidence angle")
    stats["angle"] = dict(median=np.median(Ea, axis=0), back_ka=np.median(Ba[:, 0] / Ba[:, 2]),
                          back_mvb_min=(Ba[:, 1] / Ba[:, 2]).min(), back_mvb_max=(Ba[:, 1] / Ba[:, 2]).max(),
                          back_mvb_med=np.median(Ba[:, 1] / Ba[:, 2]))
    # (c) dielectric constant (from dielectric_scan.py)
    scan = os.path.join(DATA, "dielectric_scan.npy")
    if not os.path.exists(scan):
        raise SystemExit("data/dielectric_scan.npy not found: run  python dielectric_scan.py  first (Fig. 3c)")
    res = np.load(scan, allow_pickle=True).item()
    ax = axs[2]
    eps = np.array([r["eps"] for r in res["TE"]])
    for key, ls in (("errR", "-"), ("errT", "--")):
        for k_, c in (("ka", C_KA), (2, C_2), (3, C_3)):
            if key == "errR" and k_ == 2:
                continue
            v = [r[f"{key}_{k_}"] for r in res["TE"]]
            ax.loglog(eps, v, ls, color=c, lw=1.1)
    from matplotlib.lines import Line2D
    ax.legend([Line2D([0], [0], color="k", ls="-"), Line2D([0], [0], color="k", ls="--")],
              ["reflected", "transmitted"], loc="lower right")
    ax.set_xlabel(r"$\epsilon$"); ax.set_title(r"(c) dielectric constant")
    from matplotlib.ticker import FixedLocator, FixedFormatter, NullLocator
    ticks = [1.2, 2, 3, 5, 8, 12, 16]
    ax.xaxis.set_major_locator(FixedLocator(ticks)); ax.xaxis.set_major_formatter(FixedFormatter([str(t) for t in ticks]))
    ax.xaxis.set_minor_locator(NullLocator())
    fig.tight_layout(); fig.savefig(OUT + "fig_robust.pdf"); plt.close(fig)
    return stats


if __name__ == "__main__":
    which = sys.argv[1:] or ["spectra", "robust"]
    if "spectra" in which:
        st = fig_spectra()
        print("SPECTRA (rel. L1 error: KA, n<=1, n<=2, n<=3)")
        for k in ("TE", "TM", "random"):
            print("  ", k, ["%.4f" % v for v in st[k]])
        print("   random: R exact/KA/MVB3 =", ["%.4f" % v for v in st["random_R"]], " rms slopes/k*sigma_zeta:", st["random_rms_slope"])
        print("   ensemble:", {k: (round(v, 4) if isinstance(v, float) else v) for k, v in st["ens"].items()})
    if "robust" in which:
        st = fig_robust()
        kb, E = st["conv"]
        print("ROBUST (a): kb, KA, n=1..4"); print(np.c_[kb, E])
        print("ROBUST (b):", {k: (np.round(v, 4) if hasattr(v, "__len__") else round(float(v), 4)) for k, v in st["angle"].items()})
